services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=runtracker
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
    ports:
      - '5432:5432'
